return {
  'nvim-treesitter/nvim-treesitter',

  build = ':TSUpdate',
  main = 'nvim-treesitter.configs',

  opts = {
    ensure_installed = {
      'bash',
      'c',
      'diff',
      'html',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'query',
      'vim',
      'vimdoc',
      'java',
      'python',
      'javascript',
      'typescript',
      'json',
      'yaml',
      'css',
      'scss',
      'rust',
      'go',
      'php',
      'ruby',
      'sql',
      'dockerfile',
      'make',
      'cmake',
      'toml',
      'xml',
      'terraform',
      'vue',
      'svelte',
      'graphql',
      'bash',
    },
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'ruby', 'yaml' },
    },
    indent = { enable = true, disable = { 'ruby' } },
    autotag = { enable = true },
  },
}
